### ISSUE TITLE
how can i start google browser in the OK GOOGLE ready to listen ?

### ISSUE THREAD

**Issue by FrankOcean11** [gillesdemey/google-speech-v2#14]
im not sure if this is where i want to be but it seems relevant to the same topic, what i want is to have my shortcut key in my desktop ready so when i click on it it will open up the browser in the listening mode, this way i don't have to say "ok google"  it will open ready to comply with my search.

if there a api for that in C# i would like to know about that block of code as i have my own AI C# program and at the moment it will open any webpage but it won't take my query of the bat, it will open the page for me and i will have to manually type or say "ok google" and none of the above is what im looking for.

**Comment by FrankOcean11** [comment]
no one?

**Comment by Skylion007** [comment]
This probably isn't the best tool to use explicitly for that. If you want to simply fine with "Ok Google" is spoken then you should use CMU Sphinx's library that has a keyword spotting function to determine this. Simple tasks like keyword spotting should be done locally instead of by a web based application. This is how Google does it as well so the endpoint does not have this feature  unless someone actually implements the rather complex signal processing into this particular library. 

I did implement something to filter which requests to send to Google using noise in my JARVIS speech API library in Java, but that still made a ton of requests to Google (this was before they required an API_KEY).

**Comment by FrankOcean11** [comment]
so what's the best approach  ? all i want is to say to the AI search and from there i get to also add to the ai what i will want to search for

**Comment by Skylion007** [comment]
There are several ways to implement this. This is highly technical overview
about how Google does it:
https://wiki.inf.ed.ac.uk/twiki/pub/CSTR/ListenSemester2201314/chen2014small.pdf

For the record, Windows 10 and Google Chrome already have this feature.
Best in what way? It's very abstract questions that literally thousands of
researchers are attempting to solve. Is your solution on the web? on your
phone? the easiest way, the most technical way. Regardless, this isn't
really the place to be asking those questions I would recommend a
StackOverflow Q&A style site or the such. I am by no means an expert in the
field.

**Comment by FrankOcean11** [comment]
this is just a form1 application running on my pc

**Comment by gillesdemey** [comment]
I'm going to close this issue since the question isn't very relevant to the project and the paper linked should provide sufficient information regarding keyword searching. 

Please also check out Sphinx as mentioned before for how this could be implemented.

**Comment by FrankOcean11** [comment]
wow calm down cowboy you have not answer my question as regarding keyword searching is NOT what i was looking for

**Comment by ibty** [comment]
It might not be what exactly you are looking for but take a look at this

https://github.com/ibty/ok-google-desktop
